version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,lambda,dynamodb,iam,apigateway,
      - DEBUG=1                       # Optional: Enable debug output
      - DATA_DIR=/tmp/localstack/data # Optional: Persist data across container restarts
      - LAMBDA_EXECUTOR=docker        # Required for Lambda functions using Docker
    volumes:
      - "/Users/prannoy/Projects/aws-localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
