version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:3.8.1
    network_mode: bridge  # Use host networking mode
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      #- "0.0.0.0:4566:4566"
      #- "0.0.0.0:4510-4559:4510-4559"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,lambda,dynamodb,iam,apigateway,logs,cloudwatch,route53,sts,ec2, events,ecr, ecs, efs, eks, elasticache, elasticbeanstalk, elb, elbv2, emr, eventbridge, fms, fsx, glacier, glue, guardduty, inspector2, kafka, kinesis, kms, lightsail, macie, mq, neptune, networkfirewall, opensearch, organizations, rds, redshift, resourceexplorer2, route53, s3, sagemaker, secretsmanager, securityhub, ses, shield, sns, sqs, ssm, ssmincidents, storagegateway, transfer, trustedadvisor, vpc, waf, wafv2, wellarchitected, workspaces
      - LOCALSTACK_AUTH_TOKEN=${LOCAL_STACK_HOBBY_TOKEN}
      - DEBUG=1                       # Optional: Enable debug output
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data # Optional: Persist data across container restarts
      - LAMBDA_EXECUTOR=docker        # Required for Lambda functions using Docker
    volumes:
      - "/Users/prannoy/Projects/aws-localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
